=== feordin/treasure-island/api/Data/SaveGameDataSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "SaveGameData",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "Player": {
            "type": [
                "string",
                "null"
            ]
        },
        "Score": {
            "type": "integer"
        },
        "CurrentLocation": {
            "type": [
                "string",
                "null"
            ]
        },
        "CurrentDateTime": {
            "type": "string",
            "format": "date-time"
        },
        "Inventory": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "type": "string"
            }
        },
        "Health": {
            "type": "integer"
        },
        "History": {
            "$ref": "#/definitions/CommandHistory"
        },
        "LocationChanges": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "$ref": "#/definitions/LocationChange"
            }
        }
    },
    "required": [
        "Score",
        "CurrentDateTime",
        "Health"
    ],
    "definitions": {
        "CommandHistory": {
            "type": "object",
            "properties": {
                "Command": {
                    "type": [
                        "array",
                        "null"
                    ],
                    "items": {
                        "type": "string"
                    }
                },
                "Response": {
                    "type": [
                        "array",
                        "null"
                    ],
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": []
        },
        "LocationChange": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "ItemsAdded": {
                    "type": [
                        "array",
                        "null"
                    ],
                    "items": {
                        "type": "string"
                    }
                },
                "ItemsRemoved": {
                    "type": [
                        "array",
                        "null"
                    ],
                    "items": {
                        "type": "string"
                    }
                },
                "ThingsOpened": {
                    "type": [
                        "array",
                        "null"
                    ],
                    "items": {
                        "type": "string"
                    }
                },
                "ThingsClosed": {
                    "type": [
                        "array",
                        "null"
                    ],
                    "items": {
                        "type": "string"
                    }
                },
                "ChangeTime": {
                    "type": "string",
                    "format": "date-time"
                }
            },
            "required": [
                "ChangeTime"
            ]
        }
    }
}

=== feordin/treasure-island/api/Data/startingGameData.json
{
    "$schema": "./saveGameDataSchema.json",
    "id": "start_0",
    "Player": "Jim Hawkins",
    "Score": 0,
    "CurrentLocation": "Hilltop",
    "CurrentDateTime": "1789-10-01T12:00:00Z",
    "Inventory": ["Map", "Compass"],
    "Health": 100,
    "History": {
      "Command": [],
      "Response": []
    },
    "LocationChanges": [
    ]
  }
